---
- name: git clone
  shell: git clone https://github.com/varunon9/getting-started-docker-mysql-nodejs.git
  register: clone

- debug:
    msg: "{{ clone }}"

- name: make service directory
  shell: mkdir -p /home/ubuntu/service

- name: move clone repo to that directory
  shell: cp -r /home/ubuntu/getting-started-docker-mysql-nodejs/* /home/ubuntu/service
